### ISSUE TITLE
the directory or its parent directory are not owned

### ISSUE THREAD

**Issue by poealone** [hoemotion/Karuma#1]
keep getting this message im stuck please help

The directory '/Users/JohnyTiger/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

**Comment by hoemotion** [comment]
Seems like your User profile doesn't have the permission to overwrite the folders, try running it as administrator or try https://repl.it/
Did u run the Code via terminal or via an Application like VisualStudioCode or PyCharm?
