### ISSUE TITLE
Weird error..??

### ISSUE THREAD

**Issue by zyzzed** [hoemotion/Karuma#11]
Hello! I got this weird error. Any ideas how to fix it?
_AttributeError: module 'discord' has no attribute 'Intents'_

**Comment by hoemotion** [comment]
Are you sure that you have installed the correct version of discord.py?

**Comment by 0Zombie** [comment]
Ehm yes, pretty sure...?

**Comment by hoemotion** [comment]
> Ehm yes, pretty sure...? 

Discord.py v 1.7.3 has Intents so idk what else than your discord.py version could be the problem 🤷🏻‍♂️
Maybe try uninstalling discord.py and then reinstall it 🥸?
