### ISSUE TITLE
Embed Question & Issue

### ISSUE THREAD

**Issue by mailustoday** [hoemotion/Karuma#13]
Question: Is it possible to save embeds so It's easier to send?
Issue: I was writing a description for an embed with line breaks (return) it didn't work and it would just send the first line, I tried using \n but It doesn't work.

**Comment by hoemotion** [comment]
I haven‘t added such an option yet, but you could replace in line 175 the stuff which comes after the '=' with 'yourtext \n yourtext '

**Comment by mailustoday** [comment]
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/116463050/199669772-9dedad9f-0444-4d3d-a8e8-858cd8530dc1.png">

**Comment by hoemotion** [comment]
> <img alt="image" width="1122" src="https://user-images.githubusercontent.com/116463050/199669772-9dedad9f-0444-4d3d-a8e8-858cd8530dc1.png">

Yes remove the part were it says input and just let your string there
