### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by notqizq** [hoemotion/Karuma#3]
File "<fstring>", line 1
    (await channel.create_invite())
                 ^
SyntaxError: invalid syntax

**Comment by hoemotion** [comment]
>   File "<fstring>", line 1
> 
>     (await channel.create_invite())
> 
>                  ^
> 
> SyntaxError: invalid syntax

Have you got the error instantly or after selecting smthng
You can also join the support server 
https://dsc.gg/hoemotion

**Comment by notqizq** [comment]
> >   File "<fstring>", line 1
> > 
> >     (await channel.create_invite())
> > 
> >                  ^
> > 
> > SyntaxError: invalid syntax
> 
> Have you got the error instantly or after selecting smthng
> You can also join the support server 
> https://dsc.gg/hoemotion

instantly after running, turns out i was using py 3.10 now i downgrade to 3.8 and it works

**Comment by hoemotion** [comment]
> > >   File "<fstring>", line 1
> > > 
> > >     (await channel.create_invite())
> > > 
> > >                  ^
> > > 
> > > SyntaxError: invalid syntax
> > 
> > Have you got the error instantly or after selecting smthng
> > You can also join the support server 
> > https://dsc.gg/hoemotion
> 
> instantly after running, turns out i was using py 3.10 now i downgrade to 3.8 and it works

Ok fine i will close this issue then
