### ISSUE TITLE
ugh

### ISSUE THREAD

**Issue by dropout1337** [hoemotion/Karuma#5]
Clean up your code please :sob:

**Comment by hoemotion** [comment]
> 

I will i will, when i made this code back then, i didnt know the difference between asynchronous and normal stuff

**Comment by iUseYahoo** [comment]
> Clean up your code please 😭

Does it really matter if the code isn't cleaned up? Not having a go at you but you clean it up if you want it cleaned up if you're trying to edit the code yourself.

**Comment by TheRedstoneRadiant** [comment]
Did some stuff a few months ago, feel free to merge.
https://github.com/hoemotion/Karuma/pull/4

I gave up halfway through

**Comment by 8xu** [comment]
> Did some stuff a few months ago, feel free to merge: #4
> 
> I gave up halfway through

I'm pretty sure that you closed that PR...
